const mongoose = require("mongoose");

const UserInspectionSchema = new mongoose.Schema({
  id: { type: Number },
  user_id: { type: Number },
  inspect_id: { type: String },
  status: { type: Boolean, default: true },
  is_paid: { type: Boolean, default: false },
  vehicle_year: { type: String },
  vehicle_make: { type: String },
  vehicle_model: { type: String },
  vehicle_vin: { type: String },
  vehicle_plate_no: { type: String },
  build_date: { type: String },
  comp_date: { type: String },
  no_of_keys: { type: Boolean, default: true },
  servicebook_present: { type: String },
  servicehistory_present: { type: String },
  last_service_date: { type: String },
  registration_expiry: { type: String },
  last_mileage: { type: String },
  front_wheel_d: { type: String },
  rear_wheel_d: { type: String },
  cond_front_left: { type: String },
  cond_front_right: { type: String },
  cond_rear_right: { type: String },
  cond_rear_left: { type: String },
  cond_spare: { type: String },
  transmission: { type: String },
  body_type: { type: String },
  odometer: { type: String },
  fuel_type: { type: String },
  drive_train: { type: String },
  color: { type: String },
  road_test: { type: String },
  road_test_comments: { type: String },
  general_comments: { type: String },
  is_pdf_generated: { type: Boolean, default: false },
  is_locked: { type: Boolean, default: false },
  locked_by: { type: String },
  approved_by: { type: String },
  approved_on: { type: Date },
  report_date: { type: Date },
  inspector_notes: { type: String },
  created_at: { type: Date, default: Date.now },
  updated_at: { type: Date, default: Date.now },
  deleted_at: { type: Date },
  page_status: { type: Boolean, default: false },
}, {
  collection: 'user_inspections',
  versionKey: false
});
module.exports = mongoose.model('UserInspection', UserInspectionSchema);